import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jamie's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-blue-500 p-4">
          <div className="container mx-auto flex items-center justify-between">
            {/* Logo */}
            <div className="text-white text-xl font-bold">Jamies Portfolio</div>

            {/* Navigation Links */}
            <ul className="flex space-x-4">
              <li>
                <a href="/" className="text-white">
                  Home
                </a>
              </li>
              <li>
                <a href="/projects" className="text-white">
                  Projects
                </a>
              </li>
            </ul>
          </div>
        </nav>
        {children}

        <footer className="bg-blue-500 p-4 text-white text-center">
          <div className="container mx-auto">
            &copy; {new Date().getFullYear()} Jamie's Portfolio
          </div>

          <div className="container mx-auto flex items-center justify-center">
            <Link href="https://www.linkedin.com/in/jamie-murphy-57240b270">
              <img
                src="./images/linkedin.png"
                alt="Linkedin"
                className="w-10 h-10"
              ></img>
            </Link>
            <Link href="https://github.com/JayMurphy45">
              <img
                src="./images/github.webp"
                alt="Linkedin"
                className="w-10 h-10"
              ></img>
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
